version: "3.8"
services:
  app:
    build: .
    container_name: food-ordering-application
    image: springboot-food-ordering-application:v0.0.1
    restart: always
    ports:
      - "8081:8080"
    networks:
      - food-ordering-application_common-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/food_ordering_application?allowPublicKeyRetrieval=true&autoReconnect=true&useSSL=false
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
#    platform: linux/amd64
    container_name: mysqldb
    restart: always
    networks:
      - food-ordering-application_common-net
    environment:
        MYSQL_ROOT_PASSWORD: pasindu123
        MYSQL_DATABASE: food_ordering_application
        MYSQL_USER: pasindu
        MYSQL_PASSWORD: pasindu123
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=caching_sha2_password

volumes:
  db_data:

networks:
  food-ordering-application_common-net:
